// Generated by gir (https://github.com/gtk-rs/gir @ 5bbf6cb)
// from ../../gir-files (@ 8e47c67)
// DO NOT EDIT

mod agent;
pub use self::agent::Agent;

mod candidate;
pub use self::candidate::Candidate;

mod enums;
pub use self::enums::{
  CandidateTransport, CandidateType, Compatibility, ComponentState, RelayType,
};

mod flags;
use nice_sys as ffi;

#[cfg(any(feature = "v0_1_15", feature = "dox"))]
#[cfg_attr(feature = "dox", doc(cfg(feature = "v0_1_15")))]
pub use self::flags::AgentOption;

pub fn debug_enable(with_stun: bool) {
  unsafe {
    ffi::nice_debug_enable(with_stun as i32);
  }
}

pub fn debug_disable(with_stun: bool) {
  unsafe {
    ffi::nice_debug_disable(with_stun as i32);
  }
}
